modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MORIMORI0317/BetterTaskbar/issues"
license="GNU LGPLv3"

[[mods]]
modId = "bettertaskbar"
version = "${version}"
displayName = "Better Taskbar"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/better-taskbar"
authors="MORIMORI0317"
logoFile = "logo.png"
description = '''
This mod modifies the taskbar
The ikisugi taskbar mod...
'''

[modproperties.bettertaskbar]
catalogueImageIcon = "icon.png"

[[dependencies.bettertaskbar]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bettertaskbar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"