modLoader="javafml"
loaderVersion="[38,)"
license="GNU LGPLv3"
[[mods]]
modId="bettertaskbar"
version="${file.jarVersion}"
displayName="Better Taskbar"
logoFile="logo.png"
authors="MORIMORI0317"
description='''
This mod modifies the taskbar
The Ikisugi MOD...
'''