/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class net_morimori0317_bettertaskbar_jni_win_WindowsNative */

#ifndef _Included_net_morimori0317_bettertaskbar_jni_win_WindowsNative
#define _Included_net_morimori0317_bettertaskbar_jni_win_WindowsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_morimori0317_bettertaskbar_jni_win_WindowsNative
 * Method:    setTaskbarProgressValue
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_net_morimori0317_bettertaskbar_jni_win_WindowsNative_setTaskbarProgressValue
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     net_morimori0317_bettertaskbar_jni_win_WindowsNative
 * Method:    setTaskbarProgressState
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_net_morimori0317_bettertaskbar_jni_win_WindowsNative_setTaskbarProgressState
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
