name: Java CI with Gradle

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build publish curseforge publishModrinth --stacktrace
      env:
        curesforgeapikey: ${{secrets.CURESFORGEAPIKEY}}
        modrinthapikey: ${{secrets.MODRINTH}}
        mavenpassword: ${{secrets.MAVEN}}
    - name: Zip create
      run: |
       cd build/libs
       zip release *.*
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: GMRG-Release
        path: build/libs
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: BetterTaskbar - ${{ github.ref }}
          body: |
            The New Release!
            Build by ${{ github.actor }}
          draft: false
          prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }} 
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/release.zip
          asset_name: BetterTaskbar.zip
          asset_content_type: application/zip
